# Generated by Django 2.2 on 2023-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('duration', models.IntegerField(blank=True, default=3, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
