# Generated by Django 4.1.6 on 2023-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
